In [1]:
import numpy as np
import pandas as pd

In [2]:
Data=[]
XYDAT=np.zeros((50,10))##extract all xy positions
cnt=0
i=0
with open("real_positions2.dat",'r') as f:
    for line in f:
       
        if cnt%6==0:
            cnt=1
            
        else:
            line=line.replace('\n','')
            line=line.replace("   "," ")
            line=line.replace("  "," ")
            line=line.split(" ")
            gone=0
            while gone==0:
                try:
                    line.remove('')
                except ValueError:
                    gone=1   
            
            XYDAT[i,2*(cnt-1)]=float(line[0])
            XYDAT[i,2*(cnt-1)+1]=float(line[1])
            cnt+=1
            if cnt%6==0:
                i+=1
            
XYC0=np.concatenate((XYDAT[:,0:2],XYDAT[:,2:4]-XYDAT[:,0:2],(XYDAT[:,4:6]-XYDAT[:,0:2]),(XYDAT[:,6:8]-XYDAT[:,0:2]),(XYDAT[:,8:10]-XYDAT[:,0:2])),1)        

        
        
      
    

In [34]:
print(XYC0[25,:])

[ 0.    0.    0.88  1.15  0.   -1.35  0.93 -0.95 -1.13  0.45]


In [4]:
R1=np.sqrt(XYC0[:,2]**2+XYC0[:,3]**2)
R2=np.sqrt(XYC0[:,4]**2+XYC0[:,5]**2)
R3=np.sqrt(XYC0[:,6]**2+XYC0[:,7]**2)
R4=np.sqrt(XYC0[:,8]**2+XYC0[:,9]**2)
T1=np.arctan(XYC0[:,3]/XYC0[:,2])*180/np.pi
T2=np.arctan(XYC0[:,5]/XYC0[:,4])*180/np.pi
T3=np.arctan(XYC0[:,7]/XYC0[:,6])*180/np.pi
T4=np.arctan(XYC0[:,9]/XYC0[:,8])*180/np.pi
N1=np.where(XYC0[:,2]<0)
N2=np.where(XYC0[:,4]<0)
N3=np.where(XYC0[:,6]<0)
N4=np.where(XYC0[:,8]<0)
T1[N1]=T1[N1]+180
T2[N2]=T2[N2]+180
T3[N3]=T3[N3]+180
T4[N4]=T4[N4]+180
i1=np.where(T1<0)
i2=np.where(T2<0)
i3=np.where(T3<0)
i4=np.where(T4<0)
T1[i1]=T1[i1]+360
T2[i2]=T2[i2]+360
T3[i3]=T3[i3]+360
T4[i4]=T4[i4]+360
R2=R2/R1
R3=R3/R1
R4=R4/R1
T2=T2-T1
T3=T3-T1
T4=T4-T1
I2=np.where(T2<0)
I3=np.where(T3<0)
I4=np.where(T4<0)
T2[I2]=T2[I2]+360
T3[I3]=T3[I3]+360
T4[I4]=T4[I4]+360
G4=np.where(T3>T4)
T2[G4]=360.0-T2[G4]
T3[G4]=360.0-T3[G4]
T4[G4]=360.0-T4[G4]
T12=np.abs(T2)
T23=np.abs(T3-T2)
T34=np.abs(T4-T3)

REAL_DAT=np.zeros((50,9))
REAL_DAT[:,2]=T12
REAL_DAT[:,3]=T34
REAL_DAT[:,4]=T23
REAL_DAT[:,6]=R2
REAL_DAT[:,7]=R3
REAL_DAT[:,8]=R4
FRAME=pd.DataFrame(REAL_DAT,columns=['xs','ys','the12','the34','the23','sock','d1','d2','d3'])
FRAME.to_csv("/home/jon/Lens_Bois/real_quads_processed.dat",sep=" ",index=False)

/home/jon/.local/lib/python3.6/site-packages/ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


In [5]:
REAL_DAT

array([[  0.        ,   0.        , 150.77497795,  91.35564519,
          1.53601853,   0.        ,   0.57953456,   0.57580073,
          0.52157548],
       [  0.        ,   0.        ,  79.82445586, 163.21256891,
         10.24848768,   0.        ,   1.00753136,   0.99743556,
          0.61822978],
       [  0.        ,   0.        ,  34.89509091, 175.19345688,
         11.66461736,   0.        ,   0.98710823,   0.97973302,
          0.38243403],
       [  0.        ,   0.        , 155.54844728, 101.68407704,
         15.51930445,   0.        ,   0.61587134,   0.58171761,
          0.5774103 ],
       [  0.        ,   0.        , 160.80666758,  38.49849231,
         17.51664565,   0.        ,   0.74959582,   0.73577012,
          0.73110346],
       [  0.        ,   0.        , 101.5276757 , 144.06326365,
         19.08261124,   0.        ,   0.92660169,   0.90664582,
          0.69528557],
       [  0.        ,   0.        , 128.02723071, 136.91087267,
         21.18834575,   0.    

In [89]:
a=np.zeros((2,2))
a[:,0]=1
a

array([[1., 0.],
       [1., 0.]])